name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: amadigan/github-mirror@main
        with:
          origin: 'git://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
